spring:
  config:
    activate:
      on-profile: test
  
  datasource:
    url: jdbc:h2:mem:testdb
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  
  h2:
    console:
      enabled: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600000}

# Dados de usuário para testes
test:
  user:
    name: ${TEST_USER_NAME:Admin Test}
    email: ${TEST_USER_EMAIL:admin@test.local}
    password: ${TEST_USER_PASSWORD:Test@123456}

logging:
  level:
    org.springframework.security: DEBUG
    com.github.gabrielspk: DEBUG
    org.hibernate.SQL: DEBUG