spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cadastroos?useSSL=false&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:senha}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update   # Cria/atualiza tabelas automaticamente
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  h2:
    console:
      enabled: false     # Desabilita console H2 (não será mais usado)

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600000}

dev:
  user:
    name: ${DEV_USER_NAME:Admin Dev}
    email: ${DEV_USER_EMAIL:admin@dev.local}
    password: ${DEV_USER_PASSWORD:Dev@123456}
  seed:
    enabled: ${DEV_SEED_ENABLED:true}

logging:
  level:
    org.springframework.security: DEBUG
    com.github.gabrielspk: DEBUG
